language: go
sudo: false
go: 1.7
before_install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
install:
  - go get -t -v ./...
script:
  - gometalinter
    --disable-all
    --enable=vet
    --enable=vetshadow
    --enable=golint
    --enable=errcheck
    --enable=ineffassign
    --enable=interfacer
    --enable=unconvert
    --enable=goconst
    --enable=gosimple
    --enable=staticcheck
    --enable=gas
    --vendor
    --tests
    ./...
  - go test -v ./...
